<?php

/**
 * WorkShiftTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WorkShiftDateTable extends PluginWorkShiftDateTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object WorkShiftTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WorkShiftDate');
    }
}

