<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2017/10/26 10:11:14

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;port=3306;dbname=orangehrm_mysql',
  'username' => 'root',
  'password' => 'root',
  'attributes' => 
  array (
    'export' => 'tables',
  ),
  'name' => 'doctrine',
)),);
