<?php

/**
 * PluginLeaveType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginLeaveType extends BaseLeaveType {
    public function getDescriptiveLeaveTypeName() {
        return $this->getName() . (($this->getDeleted()) ? ' ('.__('Deleted').')' : '');
    }
    public function getLeaveIsDisables(){
    	if($this->getLeaveIsDisable()== 1){
			return '禁用';
		}else{
			return '正常';
		}
    	return true;
    }
}