<?php

/**
 * BaseHoliday
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $recurring
 * @property string $description
 * @property date $date
 * @property integer $length
 * @property integer $operational_country_id
 * @property OperationalCountry $OperationalCountry
 * 
 * @method integer            getId()                     Returns the current record's "id" value
 * @method integer            getRecurring()              Returns the current record's "recurring" value
 * @method string             getDescription()            Returns the current record's "description" value
 * @method date               getDate()                   Returns the current record's "date" value
 * @method integer            getLength()                 Returns the current record's "length" value
 * @method integer            getOperationalCountryId()   Returns the current record's "operational_country_id" value
 * @method OperationalCountry getOperationalCountry()     Returns the current record's "OperationalCountry" value
 * @method Holiday            setId()                     Sets the current record's "id" value
 * @method Holiday            setRecurring()              Sets the current record's "recurring" value
 * @method Holiday            setDescription()            Sets the current record's "description" value
 * @method Holiday            setDate()                   Sets the current record's "date" value
 * @method Holiday            setLength()                 Sets the current record's "length" value
 * @method Holiday            setOperationalCountryId()   Sets the current record's "operational_country_id" value
 * @method Holiday            setOperationalCountry()     Sets the current record's "OperationalCountry" value
 * 
 * @package    orangehrm
 * @subpackage model\leave\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseApplyOvertime extends sfDoctrineRecord
{
    public function setTableDefinition()
    {

        $this->setTableName('ohrm_overtime_list');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('emp_number', 'integer', 8, array(
             'type' => 'integer',
             'default' => '0',
             'length' => 8,
             ));
        $this->hasColumn('creat_time', 'date', 25, array(
             'type' => 'date(format)',
             'length' => 25,
             ));
        $this->hasColumn('current_day', 'date', 25, array(
             'type' => 'date',
             'length' => 25,
             ));
        $this->hasColumn('stat_time', 'time', 25, array(
             'type' => 'time',
             'length' => 25,
             ));
        $this->hasColumn('end_time', 'time', 25, array(
             'type' => 'time',
             'length' => 25,
             ));
        $this->hasColumn('content', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('is_holiday', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('status', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('operation_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
    }

    // public function setUp()
    // {
    //     parent::setUp();
    //     $this->hasOne('Employee', array(
    //          'local' => 'emp_number',
    //          'foreign' => 'emp_number'));
    // }
}